### ISSUE TITLE
Feature Request: countdown timer from last click

### ISSUE THREAD

**Issue by Carus11** [oceantume/ArtilleryCalculator#1]
It would be handy for coordination if it could listen for last click event and run a countdown so that you know when you last shot will land.

**Comment by oceantume** [comment]
> It would be handy for coordination if it could listen for last click event and run a countdown so that you know when you last shot will land.

What would you use this feature for in-game? If you see only a countdown for your last click and not for all your previous clicks would this still be useful for you?

**Comment by Carus11** [comment]
When coordinating with a squad moving in on an area you are firing upon, you can tell them when the last round in the air will hit the ground. I think keeping track of all previous clicks would make the UI too big to neatly stay on top in the corner where I currently put it.

**Comment by oceantume** [comment]
@Carus11 This feature has been released with the v1.1 of the tool. Tell me if you have any comments about it.
